---
- include: 00-facts.yml

- name: create user ssh folder
  file:
    path="{{ deploy_local_user_home }}/.ssh"
    state=directory
    mode=0700
    owner="{{ deploy_local_user }}"
  when: not deploy_encrypted_private_key

- include: 01-string.yml
  when: not deploy_use_local_file and not deploy_encrypted_private_key

- include: 01-file.yml
  when: deploy_use_local_file and not deploy_encrypted_private_key

- name: add github.com to users ssh config
  ssh_config:
    host=github.com
    hostname=github.com
    remote_user=git
    identity_file="{{ deploy_local_user_home }}/.ssh/github"
    port=22
    state=present
  when: not deploy_encrypted_private_key
