---
- name:   Registering handler
  shell:  /bin/true
  notify: remove github key

- name: create user ssh folder
  file:
    path="{{ deploy_local_user_home }}/.ssh"
    state=directory
    mode=0700
    owner="{{ deploy_local_user }}"

- name: put github key from template
  template:
    src=github_key.j2
    dest="{{ deploy_local_user_home }}/.ssh/github"
    mode=0600
    owner="{{ deploy_local_user }}"
  when: not deploy_use_local_file

- name: put github key from file
  copy:
    src="{{ deploy_github_private_key_file }}"
    dest="{{ deploy_local_user_home }}/.ssh/github"
    mode=0600
    owner="{{ deploy_local_user }}"
  when: deploy_use_local_file

- name: add github.com to users ssh config
  ssh_config:
    host=github.com
    hostname=github.com
    remote_user=git
    identity_file="{{ deploy_local_user_home }}/.ssh/github"
    port=22
    state=present
